version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:latest
    working_dir: /workspace
    volumes:
      - .:/workspace
    env_file:
      - path: .env
        required: false
    environment:
      TF_TOKEN_app_terraform_io: ${TF_TOKEN_APP_TERRAFORM_IO:-}
      TF_VAR_cloudflare_api_token: ${CLOUDFLARE_API_TOKEN:-}
      TF_VAR_cloudflare_zone_id: ${CLOUDFLARE_ZONE_ID:-}
      TF_VAR_cloudflare_account_id: ${CLOUDFLARE_ACCOUNT_ID:-}
      TF_VAR_toropon_ip: ${TOROPON_IP:-}
      TF_VAR_argotunnel_cname_target: ${ARGOTUNNEL_CNAME_TARGET:-}
      TF_VAR_github_pages_challenge_content: ${GITHUB_PAGES_CHALLENGE_CONTENT:-}
    entrypoint: [ "terraform" ]
