name: "Terraform Plan"

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_CLI_ARGS: "-no-color"

    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4

      - run: terraform init -backend=false

      - run: terraform validate
